### ISSUE TITLE
Inviting users - selecting existing address

### ISSUE THREAD

**Issue by unplugged** [Pliohub/Plio#106]
When you click on "Invite users" and start typing a user's email address, and complete that address, everything works fine.

When you start typing a user's email address in Chrome (on Mac), and when you are presented with existing matching email addresses, and you select one, then this address gets entered into all 4 email address fields rather than the single field entry that you were intending.

When you start typing a user's email address in Safari (on Mac), and when you are presented with the dialog "AutoFill your contact info" and you select AutoFill, then the autofilled address gets entered into all 4 email address fields rather than the single field entry that you were intending.

**Comment by Praxie** [comment]
Done

**Comment by sives** [comment]
Still seeing this problem on 0.2.21 with both Chrome and Safari (see attached image)
![screen shot 2016-09-05 at 16 48 28](https://cloud.githubusercontent.com/assets/2330529/18252884/ff526244-7388-11e6-9d64-ec02944555e7.png)

**Comment by sives** [comment]
The field IDs that are being used for auto-fill are identical, when they need to be different.  This is causing all the fields to get filled in at once, when you invoke the auto-fill feature

**Comment by Praxie** [comment]
Fixed

**Comment by Praxie** [comment]
(Accidentally closed it)

**Comment by sives** [comment]
Seems to be working OK now in v0.2.26

**Comment by sives** [comment]
@Dartv This bug seems to have re-appeared in both the 0.4.4 and 0.4.5 versions of Plio

**Comment by sives** [comment]
This bug has re-appeared in the 0.5 version of Plio

**Comment by michaelrokosh** [comment]
Hi Steve, I don't see a way to fix it. We can disable autocomplete.

**Comment by sives** [comment]
@michaelrokosh Autocomplete is a good timesaver for the user, but only if it works on a single field at a time rather than 4 fields at once.  We fixed it previously, so why can't we fix it now?

**Comment by michaelrokosh** [comment]
@sives https://i.gyazo.com/ca234e5875a1af266bc28359ad443afb.gif
I've already spent about 1 hour on investigation, this is chrome bug. If basecamp cannot fix this, that it's a sign to start looking for a workaround. The workaround would be to enable autocomplete only for the **first field.**

**Comment by unplugged** [comment]
@michaelrokosh Agreed, restricting autocomplete only for the first field is a good solution

**Comment by Dartv** [comment]
I fixed this actually. No need for workarounds
https://github.com/Pliohub/Plio/pull/2092

**Comment by michaelrokosh** [comment]
@Dartv With the latest fix the autocomplete doesn't work at all on my and Steve's machines.
Just remove any value from the autocomplete attribute for the first input:
![image](https://user-images.githubusercontent.com/2095940/62420157-5f326a80-b696-11e9-9b35-b0cea11e36f7.png)

This will enable autocomplete only for the first email address.

**Comment by michaelrokosh** [comment]
Fixed now
